/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaproject;

import com.sun.glass.events.KeyEvent;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Gueco, Gerald
 */
public class addMembers extends javax.swing.JFrame {

    /**
     * Creates new form addMembers
     */
    public addMembers() {
        initComponents();
    }

    public static int length;
    Connection con;
    Statement st;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        addMember = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        sub = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(80, 88, 108));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gym Management System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 226, 240));
        jLabel1.setText("Add New Member");

        jLabel2.setForeground(new java.awt.Color(220, 226, 240));
        jLabel2.setText("First name");

        jLabel3.setForeground(new java.awt.Color(220, 226, 240));
        jLabel3.setText("Last name");

        jLabel4.setForeground(new java.awt.Color(220, 226, 240));
        jLabel4.setText("Contact no.");

        jLabel5.setForeground(new java.awt.Color(220, 226, 240));
        jLabel5.setText("Age");

        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });

        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnameKeyTyped(evt);
            }
        });

        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numKeyTyped(evt);
            }
        });

        addMember.setBackground(new java.awt.Color(0, 204, 51));
        addMember.setForeground(new java.awt.Color(80, 88, 108));
        addMember.setText("Add");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        back1.setForeground(new java.awt.Color(80, 88, 108));
        back1.setText("Back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        sub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1 month", "3 months", "6 months", "12 months" }));

        jLabel6.setForeground(new java.awt.Color(220, 226, 240));
        jLabel6.setText("Subscription");

        jLabel7.setForeground(new java.awt.Color(220, 226, 240));
        jLabel7.setText("+63");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(fname)
                                    .addComponent(jLabel3)
                                    .addComponent(lname)
                                    .addComponent(jLabel6)
                                    .addComponent(sub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(78, 78, 78))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num)))))))
                .addGap(76, 92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// To display main menu
    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        Menu men = new Menu();
        men.show();
        dispose();
    }//GEN-LAST:event_back1ActionPerformed
// For adding records into database
    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed

        try {
            String FNAME = fname.getText();
            String LNAME = lname.getText();
            String AGE = age.getText();
            String CONTACT = num.getText();
            String value = sub.getSelectedItem().toString();
            String amount;
            String status = "NOT PAID";

            if (FNAME.equals("") || LNAME.equals("") || AGE.equals("") || CONTACT.equals("") || value.equals("")) {
                throw new NullPointerException();
            } else {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/members", "usn", "123");
                st = con.createStatement();
                int size = CONTACT.length();
                int n = Integer.parseInt(age.getText());
                if (n < 18 || n > 50) {
                    JOptionPane.showMessageDialog(this, "Age must be 18 and above or 50 below!", "Error", JOptionPane.ERROR_MESSAGE);
                    age.setText("");
                } else if (size != 10) {
                    JOptionPane.showMessageDialog(this, "Contact no. must be 10 digits!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (value.equals("1 month")) {  
                        amount = "3800.00";
                        st.execute("INSERT INTO Members (fname, lname, age, contact, subscription, amount, status) "
                                + "VALUES('" + FNAME + "','" + LNAME + "','" + AGE + "','" + CONTACT + "','" + value + "','" + amount + "','" + status + "')");
                    }
                    if (value.equals("3 months")) {
                        amount = "8400.00";
                        st.execute("INSERT INTO Members (fname, lname, age, contact, subscription, amount, status) "
                                + "VALUES('" + FNAME + "','" + LNAME + "','" + AGE + "','" + CONTACT + "','" + value + "','" + amount + "','" + status + "')");
                    }
                    if (value.equals("6 months")) {
                        amount = "16500.00";
                        st.execute("INSERT INTO Members (fname, lname, age, contact, subscription, amount, status) "
                                + "VALUES('" + FNAME + "','" + LNAME + "','" + AGE + "','" + CONTACT + "','" + value + "','" + amount + "','" + status + "')");
                    }
                    if (value.equals("12 months")) {
                        amount = "28000.00";
                        st.execute("INSERT INTO Members (fname, lname, age, contact, subscription, amount, status) "
                                + "VALUES('" + FNAME + "','" + LNAME + "','" + AGE + "','" + CONTACT + "','" + value + "','" + amount + "','" + status + "')");
                    }

                    JOptionPane.showMessageDialog(this, "Data successfully added!");
                    fname.setText("");
                    lname.setText("");
                    age.setText("");
                    num.setText("");
                    sub.setSelectedItem("");
                }
            }
            con.close();
        } catch (NullPointerException n){
            JOptionPane.showMessageDialog(this, "Please ENTER all data!");
        } 
        catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_addMemberActionPerformed
// To input 10-digit number only
    private void numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        length = num.getText().length();

        if (length < 10) {
            num.setEditable(true);
        } else {
            if (c == KeyEvent.VK_BACKSPACE) {
                num.setEditable(true);
            } else {
                num.setEditable(false);
            }
        }
    }//GEN-LAST:event_numKeyTyped
// To input 2-digit number only
    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        length = age.getText().length();

        if (length < 2) {
            num.setEditable(true);
        } else {
            if (c == KeyEvent.VK_BACKSPACE) {
                age.setEditable(true);
            } else {
                age.setEditable(false);
            }
        }
    }//GEN-LAST:event_ageKeyTyped
// To input letters, whitespace, and backspace only in Last name
    private void lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isLetter(c) || Character.isWhitespace(c) || c == KeyEvent.VK_BACKSPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_lnameKeyTyped
// To input letters, whitespace, and backspace only in First name
    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isLetter(c) || Character.isWhitespace(c) || c == KeyEvent.VK_BACKSPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_fnameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addMembers().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMember;
    private javax.swing.JTextField age;
    private javax.swing.JButton back1;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField num;
    private javax.swing.JComboBox<String> sub;
    // End of variables declaration//GEN-END:variables
}
